# ProxySQL + MySQL 主从配置示例
# 使用方式：docker-compose -f proxysql.example.yaml up -d

version: '3.8'

services:
  # MySQL 主库
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: testdb
    command:
      - --server-id=1
      - --log-bin=mysql-bin
      - --binlog-format=ROW
    ports:
      - "3306:3306"
    volumes:
      - mysql-master-data:/var/lib/mysql
    networks:
      - db-network

  # MySQL 从库 1
  mysql-slave1:
    image: mysql:8.0
    container_name: mysql-slave1
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: testdb
    command:
      - --server-id=2
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --relay-log=relay-log
      - --read-only=1
    ports:
      - "3307:3306"
    volumes:
      - mysql-slave1-data:/var/lib/mysql
    depends_on:
      - mysql-master
    networks:
      - db-network

  # MySQL 从库 2
  mysql-slave2:
    image: mysql:8.0
    container_name: mysql-slave2
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: testdb
    command:
      - --server-id=3
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --relay-log=relay-log
      - --read-only=1
    ports:
      - "3308:3306"
    volumes:
      - mysql-slave2-data:/var/lib/mysql
    depends_on:
      - mysql-master
    networks:
      - db-network

  # ProxySQL
  proxysql:
    image: proxysql/proxysql:2.5.5
    container_name: proxysql
    ports:
      - "6033:6033"  # MySQL 协议端口（应用连接这个）
      - "6032:6032"  # 管理端口
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - mysql-master
      - mysql-slave1
      - mysql-slave2
    networks:
      - db-network

volumes:
  mysql-master-data:
  mysql-slave1-data:
  mysql-slave2-data:

networks:
  db-network:
    driver: bridge
